### PR TITLE
Multiple language fixes

### PR DESCRIPTION
**Pull request by iTitus**
Fixed all kinds of language errors.
Aligned code to some common standards.
Removed some redundant fields.
Added Mod constants and put them into use.

### CODE REVIEW

**Comment by BigXplosion** [comment]
could you explain to me what you are actually changing? The only thing I see is 2 commits which looks the same and when I press one of them my browsers start lagging out because of the 20000+ line changes... And from the stuff I can see you are just changing the formatting and breaking BCA's import order...

**Comment by iTitus** [comment]
Everywhere I changed:
handeler->handler
recepie->recipe
"bcadditions" -> Variables.Mod.MOD_ID
"Buildcraft Additions" -> Variables.Mod.NAME
"@MODVERSION@" -> Variables.Mod.VERSION
Some other minor spelling mistakes
Additionaly I added a "BCAdditionsAPIProps" class which has some constants for the API

Fixed some minor bugs I found while searching for spelling mistakes
Updated mcmod.info

**Comment by BigXplosion** [comment]
those things might be good but I don't think @AEnterprise will be pulling 20000+ line changes. You should really fix up the formatting you changes....

**Comment by iTitus** [comment]
I need the configurations AEnterprise uses then...

**Comment by BigXplosion** [comment]
or don't hit the refractor button...

**Comment by iTitus** [comment]
By mistake I hit it once on everything, but I used the undo function then.
Sorry I destroyed the import order, I thought AEnterprise used the default configuration and then it was too late :(

**Comment by BigXplosion** [comment]
you will see what @AEnterprise says about this but I think you might have to redo... sorry

**Comment by iTitus** [comment]
To my defense I have to say that those many lines accumulated mostly through removing whitespaces in empty lines. Also Git thought I rewrote the whole BuildcraftAdditions class which is not true, I only fixed spelling mistakes in the method names and in the Mod annotations I replaced the Strings with constants. Additionaly git did not recognize the renamings of patern -> pattern and recepei -> recipe as renaming but deleting the old file and creating a new one...

**Comment by iTitus** [comment]
Sadly I could not fix the capitalization of the package name because git does not recognize renaming with only case changing :(

**Comment by AEnterprise** [comment]
@iTitus to start of there is a merge conflict, probably me fixing the minetweaker integration

also i'm not pulling this do to alot of unneeded changes and i can't even see them due to how much there are, for the import settings i'll send you those later, if you want you can redo it later but then i sugest you break it up intro multiple smaller commits so i can at least see the changes made that way but i could also do it myself, in general this it's no bad idea to do this, the way if implementation wasn't done very well i'm afraid, sorry

**Comment by AEnterprise** [comment]
if you want i'll probably do it myself, i need to go over 90% of my code anyways as i'm gona unify other things as well

**Comment by iTitus** [comment]
Ok then ;)
Because BCA is open source you (and probably we too) have the responsibility to keep the code clean and right. Spelling mistakes or missing centralization via constants are bad for this. When you are ready for this refractor, you can always ask for help to give some work to others.

**Comment by AEnterprise** [comment]
first thing to do now is to unify networking, i already reduced it to a single message but all machines are still individually responsible for syncing, i'm gona refactor it away to the base class, will fix a few possible desync issues and other machines constantly updating, then i'll refactor the above things one by one in diffenrent commits so browsers don't have to much issues with it

**Comment by iTitus** [comment]
Wednesday I could redo this with smaller commits.

**Comment by AEnterprise** [comment]
@iTitus no need i'll do it myself, there are just some refacors i need to do

**Comment by iTitus** [comment]
Okay ;)

**Comment by AEnterprise** [comment]
@iTitus don't get me wrong though, i apreciate the work you've put intro finding those typo's (as i'm not fluid in english) but you don't have to go through the hassle of setting it up again, also can you join me on irc or send me your email somhow? then i send you the import order list

**Comment by iTitus** [comment]
I'll come to irc ;)

**Pull request closed without merging**
